// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSSnNrixc6G4QNNBiGmLRzzl1aBm4druc',
    appId: '1:655080324450:ios:85d51413284213418f803b',
    messagingSenderId: '655080324450',
    projectId: 'notesapp-a026b',
    storageBucket: 'notesapp-a026b.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSSnNrixc6G4QNNBiGmLRzzl1aBm4druc',
    appId: '1:655080324450:ios:85d51413284213418f803b',
    messagingSenderId: '655080324450',
    projectId: 'notesapp-a026b',
    storageBucket: 'notesapp-a026b.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL_lOyLEelC6EBUeYhfNWwZiko2qnXlp4',
    appId: '1:655080324450:web:e9f0beef61c0d3668f803b',
    messagingSenderId: '655080324450',
    projectId: 'notesapp-a026b',
    authDomain: 'notesapp-a026b.firebaseapp.com',
    storageBucket: 'notesapp-a026b.firebasestorage.app',
    measurementId: 'G-VHGJEF4VLB',
  );

}